// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stream.proto

package stream

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

// The response message
type ResponseScale struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Subtype              string   `protobuf:"bytes,4,opt,name=subtype,proto3" json:"subtype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseScale) Reset()         { *m = ResponseScale{} }
func (m *ResponseScale) String() string { return proto.CompactTextString(m) }
func (*ResponseScale) ProtoMessage()    {}
func (*ResponseScale) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{1}
}

func (m *ResponseScale) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseScale.Unmarshal(m, b)
}
func (m *ResponseScale) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseScale.Marshal(b, m, deterministic)
}
func (m *ResponseScale) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseScale.Merge(m, src)
}
func (m *ResponseScale) XXX_Size() int {
	return xxx_messageInfo_ResponseScale.Size(m)
}
func (m *ResponseScale) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseScale.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseScale proto.InternalMessageInfo

func (m *ResponseScale) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ResponseScale) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ResponseScale) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ResponseScale) GetSubtype() string {
	if m != nil {
		return m.Subtype
	}
	return ""
}

type RequestTareValue struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestTareValue) Reset()         { *m = RequestTareValue{} }
func (m *RequestTareValue) String() string { return proto.CompactTextString(m) }
func (*RequestTareValue) ProtoMessage()    {}
func (*RequestTareValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{2}
}

func (m *RequestTareValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestTareValue.Unmarshal(m, b)
}
func (m *RequestTareValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestTareValue.Marshal(b, m, deterministic)
}
func (m *RequestTareValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestTareValue.Merge(m, src)
}
func (m *RequestTareValue) XXX_Size() int {
	return xxx_messageInfo_RequestTareValue.Size(m)
}
func (m *RequestTareValue) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestTareValue.DiscardUnknown(m)
}

var xxx_messageInfo_RequestTareValue proto.InternalMessageInfo

func (m *RequestTareValue) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RequestScale struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Subtype              string   `protobuf:"bytes,3,opt,name=subtype,proto3" json:"subtype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestScale) Reset()         { *m = RequestScale{} }
func (m *RequestScale) String() string { return proto.CompactTextString(m) }
func (*RequestScale) ProtoMessage()    {}
func (*RequestScale) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{3}
}

func (m *RequestScale) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestScale.Unmarshal(m, b)
}
func (m *RequestScale) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestScale.Marshal(b, m, deterministic)
}
func (m *RequestScale) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestScale.Merge(m, src)
}
func (m *RequestScale) XXX_Size() int {
	return xxx_messageInfo_RequestScale.Size(m)
}
func (m *RequestScale) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestScale.DiscardUnknown(m)
}

var xxx_messageInfo_RequestScale proto.InternalMessageInfo

func (m *RequestScale) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RequestScale) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *RequestScale) GetSubtype() string {
	if m != nil {
		return m.Subtype
	}
	return ""
}

type ResponseSetScale struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseSetScale) Reset()         { *m = ResponseSetScale{} }
func (m *ResponseSetScale) String() string { return proto.CompactTextString(m) }
func (*ResponseSetScale) ProtoMessage()    {}
func (*ResponseSetScale) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{4}
}

func (m *ResponseSetScale) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseSetScale.Unmarshal(m, b)
}
func (m *ResponseSetScale) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseSetScale.Marshal(b, m, deterministic)
}
func (m *ResponseSetScale) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseSetScale.Merge(m, src)
}
func (m *ResponseSetScale) XXX_Size() int {
	return xxx_messageInfo_ResponseSetScale.Size(m)
}
func (m *ResponseSetScale) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseSetScale.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseSetScale proto.InternalMessageInfo

func (m *ResponseSetScale) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ResponseInstantWeight struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseInstantWeight) Reset()         { *m = ResponseInstantWeight{} }
func (m *ResponseInstantWeight) String() string { return proto.CompactTextString(m) }
func (*ResponseInstantWeight) ProtoMessage()    {}
func (*ResponseInstantWeight) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{5}
}

func (m *ResponseInstantWeight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseInstantWeight.Unmarshal(m, b)
}
func (m *ResponseInstantWeight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseInstantWeight.Marshal(b, m, deterministic)
}
func (m *ResponseInstantWeight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseInstantWeight.Merge(m, src)
}
func (m *ResponseInstantWeight) XXX_Size() int {
	return xxx_messageInfo_ResponseInstantWeight.Size(m)
}
func (m *ResponseInstantWeight) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseInstantWeight.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseInstantWeight proto.InternalMessageInfo

func (m *ResponseInstantWeight) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ResponseInstantWeight) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "stream.Empty")
	proto.RegisterType((*ResponseScale)(nil), "stream.ResponseScale")
	proto.RegisterType((*RequestTareValue)(nil), "stream.RequestTareValue")
	proto.RegisterType((*RequestScale)(nil), "stream.RequestScale")
	proto.RegisterType((*ResponseSetScale)(nil), "stream.ResponseSetScale")
	proto.RegisterType((*ResponseInstantWeight)(nil), "stream.ResponseInstantWeight")
}

func init() {
	proto.RegisterFile("stream.proto", fileDescriptor_bb17ef3f514bfe54)
}

var fileDescriptor_bb17ef3f514bfe54 = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xdd, 0x6a, 0x32, 0x31,
	0x10, 0x75, 0xfd, 0xff, 0x06, 0xfd, 0x90, 0xa0, 0x74, 0x11, 0x0a, 0x25, 0x57, 0x5e, 0x14, 0x5b,
	0x6c, 0x5f, 0xa0, 0xda, 0x22, 0x85, 0x96, 0x82, 0x5b, 0x2c, 0x78, 0x17, 0xcb, 0xa0, 0xc2, 0xfe,
	0x35, 0x99, 0xbd, 0xf0, 0x0d, 0xfa, 0xd8, 0xc5, 0x24, 0x6b, 0x77, 0xd7, 0x2a, 0x78, 0x97, 0x99,
	0x39, 0x33, 0x73, 0xce, 0x1c, 0x02, 0x2d, 0x45, 0x12, 0x45, 0x30, 0x8c, 0x65, 0x44, 0x11, 0xab,
	0x9b, 0x88, 0x37, 0xa0, 0xf6, 0x14, 0xc4, 0xb4, 0xe5, 0x01, 0xb4, 0x67, 0xa8, 0xe2, 0x28, 0x54,
	0xe8, 0x7d, 0x0a, 0x1f, 0x59, 0x17, 0x6a, 0x28, 0x65, 0x24, 0x5d, 0xe7, 0xca, 0x19, 0xfc, 0x9b,
	0x99, 0x80, 0xb9, 0xd0, 0x08, 0x50, 0x29, 0xb1, 0x42, 0xb7, 0xac, 0xf3, 0x69, 0xc8, 0x18, 0x54,
	0x69, 0x1b, 0xa3, 0x5b, 0xd1, 0x69, 0xfd, 0xde, 0xa1, 0x55, 0xb2, 0xd4, 0xe9, 0xaa, 0x41, 0xdb,
	0x90, 0x5f, 0x43, 0x67, 0x86, 0x5f, 0x09, 0x2a, 0x7a, 0x17, 0x12, 0xe7, 0xc2, 0x4f, 0x30, 0x3b,
	0xdb, 0xc9, 0xcd, 0xe6, 0x73, 0x68, 0x59, 0xb4, 0xe1, 0x76, 0x14, 0xb9, 0x67, 0x51, 0xfe, 0x9b,
	0x45, 0x25, 0xcf, 0x62, 0xb0, 0x63, 0x61, 0x45, 0x23, 0x9d, 0xd0, 0xcd, 0xa7, 0xd0, 0x4b, 0x91,
	0xcf, 0xa1, 0x22, 0x11, 0xd2, 0x07, 0x6e, 0x56, 0x6b, 0x3a, 0xf7, 0x4c, 0xa3, 0xef, 0x0a, 0xfc,
	0x7f, 0x88, 0x37, 0x13, 0xe1, 0xfb, 0x28, 0xcd, 0xc6, 0x17, 0xb8, 0xd0, 0x0f, 0xf5, 0x6a, 0x30,
	0x6f, 0x09, 0x4d, 0xd6, 0x22, 0x0c, 0xd1, 0x67, 0xdd, 0xa1, 0x75, 0x2d, 0x2b, 0xbf, 0xdf, 0xfb,
	0xcd, 0x66, 0x1c, 0xe3, 0xa5, 0x81, 0x73, 0xeb, 0xb0, 0x7b, 0x68, 0x78, 0xa8, 0xaf, 0xca, 0xda,
	0x29, 0x4e, 0x5b, 0xdc, 0x77, 0x0f, 0xda, 0xac, 0x66, 0x5e, 0x62, 0x8f, 0xd0, 0xb2, 0x5d, 0xd6,
	0x8b, 0xc2, 0xe2, 0x7d, 0xe5, 0xe4, 0x14, 0xb3, 0x7b, 0x81, 0x32, 0x3a, 0x67, 0xf7, 0x18, 0x3a,
	0x53, 0xa4, 0xfc, 0x59, 0x0b, 0xed, 0x97, 0xc5, 0xf6, 0x1c, 0x9a, 0x97, 0xd8, 0x08, 0x9a, 0x53,
	0x24, 0x8f, 0x04, 0x1d, 0xc8, 0x3e, 0x76, 0xad, 0x31, 0x2c, 0x9a, 0xc3, 0x1b, 0x53, 0x5b, 0xd6,
	0xf5, 0xb7, 0xb8, 0xfb, 0x09, 0x00, 0x00, 0xff, 0xff, 0x43, 0xd3, 0xae, 0xe1, 0x26, 0x03, 0x00,
	0x00,
}
